name: GitHub-Skill-Icons

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - name: Get SVG dark
        run: |
          curl -o ./skill-icons/skill-icons-dark.svg  "https://devicons.acavalkyrie.workers.dev/icons?i=platformio%2Cavr%2Cespressifsystems%2Carduino%2Craspberrypi%2Crust%2Cc%2Ccpp%2Ccs%2Cdotnet%2Cpy%2Cjs%2Cbash%2Cselenium%2Cdocker%2Cbots%2Cgodot%2Cunity%2Catom%2Cvscode%2Cvim%2Cneovim%2Cgit%2Cgithub&perline=12&theme=dark"
      - name: Get SVG light
        run: |
          curl -o ./skill-icons/skill-icons-light.svg "https://devicons.acavalkyrie.workers.dev/icons?i=platformio%2Cavr%2Cespressifsystems%2Carduino%2Craspberrypi%2Crust%2Cc%2Ccpp%2Ccs%2Cdotnet%2Cpy%2Cjs%2Cbash%2Cselenium%2Cdocker%2Cbots%2Cgodot%2Cunity%2Catom%2Cvscode%2Cvim%2Cneovim%2Cgit%2Cgithub&perline=12&theme=light"
      - name: Check for changes
        run: |
          git status
          ls -la
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add -A .
          git commit -m "generated"
          git push